### PR TITLE
CMake: Call mbed_set_post_build API for setting post build operations

### PR DESCRIPTION
**Pull request by rajkan01**
- Called mbed_set_post_build API for setting post-build operations

### CODE REVIEW

**Review by hugueskamba — APPROVED** [review]

**Review by 0xc0170 — APPROVED** [review]

**Comment by 0xc0170** [comment]
Travis needs to be migrated, doing it now

**Comment by 0xc0170** [comment]
Let me try to close and reopen. It should trigger a new  build after migration. Although it will fail

**Comment by 0xc0170** [comment]
New travis run, failed with known version issue, fix incoming

**Comment by 0xc0170** [comment]
Errors looks good, its related to MBed OS update. I'll merge this to unblock the Mbed OS PR

**Pull request merged**
