### PR TITLE
Update mbed OS hash to master

### PR DESCRIPTION
**Pull request by kegilbert**

### CODE REVIEW

**Comment by TacoGrandeTX** [comment]
Yes - this builds successfully!

**Comment by cmonr** [comment]
Why did this need to be updated to master? Is there something that came in after 5.10.4 that necessitates this?

(Also, I don't think this will be merged until after OOB, at which point, it will point to 5.11.0 anyways)

**Comment by kegilbert** [comment]
The RAM/ROM reporting came in after 5.10.4 I believe @cmonr

**Comment by cmonr** [comment]
So this raises an interesting question.

Our examples should always be pinned to a release version.

When a feature release comes around, my current understanding is that we create a release branch to test for OOB, but we don't have a way to add feature release specific changes _into_ that branch. 

Wondering what the _proper_ way of updating examples with feature release specific changes, when the OOB branch isn't created until the RC is made.

@ARMmbed/mbed-os-maintainers Thoughts?

**Comment by kegilbert** [comment]
Closing this, #147 reverts the breaking change. The OOB branch has the updated hashes and works. This will be readded following the release.

**Pull request closed without merging**
